import localFont from "next/font/local";
import Head from "next/head";
import "./globals.css";

// Importing custom fonts with variable weights
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
  display: "swap", // Display swap to improve loading performance
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
  display: "swap",
});

// Metadata for the document head
export const metadata = {
  title: "CHAT-GPT2",
  description: "Generated by BitStudents",
  keywords: "AI chatbot, GPT, Chatbot UI, AI applications",
  robots: "index, follow",
  openGraph: {
    title: "CHAT-GPT2 - BitStudents",
    description: "A next-gen AI chatbot interface.",
    url: "https://your-domain.com",
    siteName: "CHAT-GPT2",
    images: [
      {
        url: "https://your-domain.com/og-image.png",
        width: 800,
        height: 600,
        alt: "CHAT-GPT2 Interface",
      },
    ],
    locale: "en_US",
    type: "website",
  },
};

// Move viewport settings to a separate export as required by Next.js
export const viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* Preloading fonts for improved performance */}
      <Head>
        <link rel="preload" href="./fonts/GeistVF.woff" as="font" type="font/woff" crossOrigin="anonymous" />
        <link rel="preload" href="./fonts/GeistMonoVF.woff" as="font" type="font/woff" crossOrigin="anonymous" />
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100 dark:bg-gray-900 text-gray-800 dark:text-gray-200 transition-colors duration-300`}
      >
        {/* Container for the chat UI, ensuring responsiveness */}
        <div className="container mx-auto px-4 py-8 min-h-screen">
          {children}
        </div>
      </body>
    </html>
  );
}
