import localFont from "next/font/local";
import "./globals.css";

// Importing custom fonts with variable weights using Next.js Font API
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
  display: "swap", // Display swap to improve loading performance
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
  display: "swap",
});

// Using the Metadata API for head configuration
export const metadata = {
  title: "CHAT-GPT2",
  description: "Generated by BitStudents",
  keywords: "AI chatbot, GPT, Chatbot UI, AI applications",
  robots: "index, follow",
  openGraph: {
    title: "CHAT-GPT2 - BitStudents",
    description: "A next-gen AI chatbot interface.",
    url: "https://your-domain.com",
    siteName: "CHAT-GPT2",
    images: [
      {
        url: "https://your-domain.com/og-image.png",
        width: 800,
        height: 600,
        alt: "CHAT-GPT2 Interface",
      },
    ],
    locale: "en_US",
    type: "website",
  },
};

// Additional metadata for viewport settings
export const viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
};

// RootLayout component for the app directory structure
export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="antialiased bg-gray-100 dark:bg-gray-900 text-gray-800 dark:text-gray-200 transition-colors duration-300">
        {/* Container for the chat UI, ensuring responsiveness */}
        <div className="container mx-auto px-4 py-8 min-h-screen">{children}</div>
      </body>
    </html>
  );
}
